on: push
name: Continuous Integration
jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        otp: [22.3]
        elixir: [1.10.2]

    env:
      MIX_ENV: test
    steps:
      - uses: actions/checkout@v1.0.0

      - name: Cache dialyzer plts
        uses: actions/cache@v1
        with:
          path: priv/plts
          key: ${{runner.os}}-${{matrix.otp}}-${{matrix.elixir}}-plts

      - uses: actions/setup-elixir@v1.0.0
        with:
          otp-version: ${{matrix.otp}}
          elixir-version: ${{matrix.elixir}}
      - name: Deps get
        run: mix deps.get
      - name: Check Credo
        run: mix credo --strict
      - name: Check Formatting
        run: mix format --check-formatted
      - name: Run Tests
        run: mix do compile --warnings-as-errors, test
      - name: Dialyzer
        run: MIX_ENV=dev mix dialyzer
